export default {
  //Network info
  Get_NETWORK_INFO_REQUEST: "Get_NETWORK_INFO_REQUEST",
  Get_NETWORK_INFO_SUCCESS: "Get_NETWORK_INFO_SUCCESS",
  //LOGIN
  LOGIN_USER_REQUEST: "LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",
  //gget MENU
  GET_ALL_MENU_REQUEST: "GET_ALL_MENU_REQUEST",
  GET_ALL_MENU_SUCCESS: "GET_ALL_MENU_SUCCESS",
  GET_ALL_MENU_FAIL: "GET_ALL_MENU_FAIL",
  //Get deals
  GET_DEALS_REQUEST: "GET_DEALS_REQUEST",
  GET_DEALS_SUCCESS: "GET_DEALS_SUCCESS",
  GET_DEALS_FAIL: "GET_DEALS_FAIL",
  //logout
  LOGIN_LOGOUT_REQUEST: "LOGIN_LOGOUT_REQUEST",
  LOGIN_LOGOUT_SUCCESS: "LOGIN_LOGOUT_SUCCESS",
  //Cart detail
  GET_CART_DETAIL_REQUEST: "GET_CART_DETAIL_REQUEST",
  GET_CART_DETAIL_SUCCESS: "GET_CART_DETAIL_SUCCESS",
  GET_CART_DETAIL_FAILURE: "GET_CART_DETAIL_FAILURE",

   //Cart detail
   GET_ORDER_HISTORY_REQUEST: "GET_ORDER_HISTORY_REQUEST",
   GET_ORDER_HISTORY_SUCCESS: "GET_ORDER_HISTORY_SUCCESS",
   GET_ORDER_HISTORY_FAILURE: "GET_ORDER_HISTORY_FAILURE",
   //get profile
  GET_PROFILE_REQUEST: "GET_PROFILE_REQUEST",
  GET_PROFILE_SUCCESS: "GET_PROFILE_SUCCESS",
  GET_PROFILE_FAILURE: "GET_PROFILE_FAILURE",
};
